# Generated by Django 2.0.1 on 2018-01-16 12:11

from django.db import migrations, models
import django.db.models.deletion
import edc_base.sites.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ambition_screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subjectscreening',
            managers=[
                ('on_site', edc_base.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
    ]
